// Copyright 2024-2026 Netcracker Technology Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"authz-agent/components/pap-client/internal/policyadmin"
	"authz-agent/internal/pips"
)

func main() {
	logger := log.New(os.Stdout, "[pap-client] ", log.LstdFlags)

	// Subcommands.
	if len(os.Args) > 1 {
		switch os.Args[1] {
		case "bootstrap":
			runBootstrap(logger)
			return
		case "healthcheck":
			// --readiness adds the "policies loaded" gate on top of the
			// liveness conditions (OPA ready + JWKS bootstrap).  Liveness uses
			// the plain healthcheck so that a temporary access-control failure
			// does not restart the container while its cached policies are valid.
			readiness := len(os.Args) > 2 && os.Args[2] == "--readiness"
			runHealthcheck(logger, readiness)
			return
		}
	}

	entitlementsCfg := pips.LoadEntitlementsConfigFromEnv()
	if entitlementsCfg != nil {
		logger.Printf(
			"entitlements PIP configured: url=%s httpTimeoutSeconds=%d httpRetries=%d (ADR-0054)",
			entitlementsCfg.URL,
			entitlementsCfg.HTTPTimeoutSeconds,
			entitlementsCfg.HTTPRetries,
		)
	}

	// OPA write-path authentication (authz-agent-ADR-0077).
	// Read the shared secret that was generated by the Helm chart and written
	// to disk by the start script. This token is sent as Authorization: Bearer
	// on every PUT/PATCH request to OPA's data API so that system_authz.rego
	// can verify the caller's identity before allowing writes.
	opaAuthToken := readOPAAuthToken(logger)

	policyFile := getenv("AUTHZ_POLICY_DATA_FILE", policyadmin.DefaultPolicyFile)
	pipFile := getenv("AUTHZ_PIP_DATA_FILE", policyadmin.DefaultPIPFile)

	// Pull status file: written by PolicyPuller / MountWatcher after the first
	// successful apply.  Read by "pap-client healthcheck --readiness" and by
	// the /health handler, which reports the last conversion counts from it.
	// Shared between both delivery modes — whichever mode runs writes it.
	pullStatusFile := getenv("AUTHZ_PULL_STATUS_FILE", policyadmin.DefaultPullStatusFile)

	server := policyadmin.New(policyadmin.Config{
		ListenAddr:              getenv("AUTHZ_PAP_CLIENT_ADDR", policyadmin.DefaultListenAddr),
		PullStatusFile:          pullStatusFile,
		RequestBodyLimit:        envInt64("AUTHZ_PAP_CLIENT_REQUEST_LIMIT_BYTES", policyadmin.DefaultRequestLimit),
		HTTPClient:              &http.Client{Timeout: 10 * time.Second},
		Logger:                  logger,
		DecisionLogFile:         getenv("AUTHZ_DECISION_LOG_FILE", policyadmin.DefaultDecisionLogFile),
		DecisionLogIngestPath:   getenv("AUTHZ_DECISION_LOG_INGEST_PATH", policyadmin.DefaultDecisionLogIngestPath),
		DecisionLogDownloadPath: getenv("AUTHZ_DECISION_LOG_DOWNLOAD_PATH", policyadmin.DefaultDecisionLogDownloadPath),
	}).Server()

	// Trusted providers are mounted from a ConfigMap; watch the file so an
	// operator can add or retire an IdP without restarting the Pod
	// (authz-agent-ADR-0070). Set the interval to 0 to disable.
	reloadInterval := envSeconds(
		"AUTHZ_TRUSTED_PROVIDERS_RELOAD_INTERVAL",
		policyadmin.DefaultProvidersReloadInterval,
	)
	go policyadmin.NewProvidersReloader(
		bootstrapConfigFromEnv(logger),
		opaAuthnDataURL(),
		reloadInterval,
		opaAuthToken,
	).Run(context.Background())

	// Policy delivery mode: presence of the ConfigMap mount directory at
	// startup selects the mount watcher; absence selects the pull loop.
	// The mount wins and disables the pull, so no flag is needed — log which
	// path was chosen so an operator who accidentally mounted a ConfigMap can
	// see why nothing is being pulled (ADR-0071 §Delivery modes).
	mountDir := getenv("AUTHZ_POLICY_MOUNT_DIR", policyadmin.PolicyMountDir)
	pullInterval := envSeconds("AUTHZ_PAP_CLIENT_PULL_INTERVAL", policyadmin.DefaultPullInterval)
	opaPolURL := opaDataURL()
	opaPIPURL := opaPIPDataURL()

	// Token file watcher: publishes the current M2M token (projected SA token
	// or Keycloak token from the token-fetcher sidecar) to OPA as
	// data.m2m.bearerToken on every detected content change. Works in both
	// KUBERNETES_M2M_ENABLED modes. Shares the OPA auth client so the PUT to
	// /v1/data/m2m carries the write-path bearer token (ADR-0077).
	//
	// Deliberately NOT opaPIPURL: the puller below replaces /v1/data/pips
	// wholesale every tick, which would erase the token. One writer per
	// document root — see policyadmin.TokenWatcher.
	//
	// M2MFile: also writes the token to disk so OPA can reload data.m2m from
	// the shared opa-data volume after a restart without waiting for the next
	// watcher tick.
	go policyadmin.NewTokenWatcher(policyadmin.TokenWatcherConfig{
		TokenFile:  getenv("AUTHZ_PAP_CLIENT_TOKEN_FILE", policyadmin.DefaultACTokenFile),
		OPAM2MURL:  opaM2MDataURL(),
		M2MFile:    getenv("AUTHZ_M2M_DATA_FILE", policyadmin.DefaultM2MFile),
		Logger:     logger,
		HTTPClient: policyadmin.NewOPAClient(opaAuthToken, 10*time.Second),
	}).Run(context.Background())

	if fi, err := os.Stat(mountDir); err == nil && fi.IsDir() {
		logger.Printf("policy delivery: ConfigMap mount at %s (pull loop disabled)", mountDir)
		go policyadmin.NewMountWatcher(policyadmin.MountWatchConfig{
			MountDir:       mountDir,
			Interval:       pullInterval,
			PolicyFile:     policyFile,
			PIPFile:        pipFile,
			OPAPoliciesURL: opaPolURL,
			OPAPIPsURL:     opaPIPURL,
			Entitlements:   entitlementsCfg,
			OPAAuthToken:   opaAuthToken,
			PullStatusFile: pullStatusFile,
			Logger:         logger,
		}).Run(context.Background())
	} else {
		logger.Printf("policy delivery: pull loop (mount %s absent)", mountDir)
		go policyadmin.NewPolicyPuller(policyadmin.PullConfig{
			SourceURL:      getenv("AUTHZ_PAP_CLIENT_SOURCE_URL", ""),
			Interval:       pullInterval,
			TokenFile:      getenv("AUTHZ_PAP_CLIENT_TOKEN_FILE", policyadmin.DefaultACTokenFile),
			PolicyFile:     policyFile,
			PIPFile:        pipFile,
			OPAPoliciesURL: opaPolURL,
			OPAPIPsURL:     opaPIPURL,
			Entitlements:   entitlementsCfg,
			OPAAuthToken:   opaAuthToken,
			PullStatusFile: pullStatusFile,
			Logger:         logger,
		}).Run(context.Background())
	}

	logger.Printf("starting on %s", server.Addr)
	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		logger.Fatalf("server failed: %v", err)
	}
}

// readOPAAuthToken reads the OPA write-path bearer token from the file named by
// AUTHZ_OPA_AUTH_TOKEN_FILE. An empty or absent env var returns ""; a missing
// file logs a warning and returns "". See authz-agent-ADR-0077.
func readOPAAuthToken(logger *log.Logger) string {
	tokenFile := strings.TrimSpace(os.Getenv("AUTHZ_OPA_AUTH_TOKEN_FILE"))
	if tokenFile == "" {
		return ""
	}
	data, err := os.ReadFile(tokenFile)
	if err != nil {
		logger.Printf("warn: cannot read AUTHZ_OPA_AUTH_TOKEN_FILE=%s: %v — OPA write paths will have no identity token (ADR-0077)", tokenFile, err)
		return ""
	}
	token := strings.TrimSpace(string(data))
	if token == "" {
		logger.Printf("warn: AUTHZ_OPA_AUTH_TOKEN_FILE=%s is empty — OPA write paths will have no identity token (ADR-0077)", tokenFile)
	} else {
		logger.Printf("OPA auth token loaded from %s (ADR-0077)", tokenFile)
	}
	return token
}

func getenv(key, fallback string) string {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	return value
}

func envBoolDefault(key string, fallback bool) bool {
	v := strings.TrimSpace(os.Getenv(key))
	if v == "" {
		return fallback
	}
	switch strings.ToLower(v) {
	case "1", "true", "yes", "on":
		return true
	case "0", "false", "no", "off":
		return false
	default:
		return fallback
	}
}

// envSeconds parses a whole-second duration. Unlike envInt64 it accepts 0,
// which the caller uses as "switch this off"; a malformed value falls back to
// the default rather than silently disabling a feature.
func envSeconds(key string, fallback time.Duration) time.Duration {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}

	parsed, err := strconv.ParseInt(value, 10, 64)
	if err != nil || parsed < 0 {
		return fallback
	}

	return time.Duration(parsed) * time.Second
}

func envInt64(key string, fallback int64) int64 {
	value := strings.TrimSpace(os.Getenv(key))
	if value == "" {
		return fallback
	}
	parsed, err := strconv.ParseInt(value, 10, 64)
	if err != nil || parsed <= 0 {
		return fallback
	}
	return parsed
}

func opaPIPDataURL() string {
	if explicit := strings.TrimSpace(os.Getenv("AUTHZ_PIP_ADMIN_OPA_DATA_URL")); explicit != "" {
		return explicit
	}

	opaAddr := strings.TrimSpace(os.Getenv("OPA_ADDR"))
	if opaAddr == "" {
		opaAddr = "127.0.0.1:8181"
	}

	if strings.HasPrefix(opaAddr, "http://") || strings.HasPrefix(opaAddr, "https://") {
		return strings.TrimRight(opaAddr, "/") + "/v1/data/pips"
	}

	return "http://" + opaAddr + "/v1/data/pips"
}

// opaM2MDataURL returns the OPA data API URL for the M2M credential document.
//
// This is a separate document root from the PIP configuration on purpose. OPA's
// Data API PUT replaces the document at the target path, so the TokenWatcher and
// the PolicyPuller cannot share one — see the note on policyadmin.TokenWatcher.
// It is derived from the same OPA_ADDR so the two URLs can never drift apart.
func opaM2MDataURL() string {
	if explicit := strings.TrimSpace(os.Getenv("AUTHZ_M2M_OPA_DATA_URL")); explicit != "" {
		return explicit
	}

	opaAddr := strings.TrimSpace(os.Getenv("OPA_ADDR"))
	if opaAddr == "" {
		opaAddr = "127.0.0.1:8181"
	}

	if strings.HasPrefix(opaAddr, "http://") || strings.HasPrefix(opaAddr, "https://") {
		return strings.TrimRight(opaAddr, "/") + "/v1/data/m2m"
	}

	return "http://" + opaAddr + "/v1/data/m2m"
}

// runHealthcheck performs either a liveness check or a readiness check
// depending on the readiness flag.
//
// Liveness (readiness=false): calls GET /health on the pap-client service.
// Returns 0 (success) when OPA is ready and JWKS bootstrap thresholds are met.
//
// Readiness (readiness=true): additionally reads the pull status file written by
// PolicyPuller / MountWatcher.  The Pod is not Ready until policiesLoaded=true,
// which is set after the first successful pull.  The latch is never reset, so a
// transient access-control failure does not remove the Pod from the Service.
// When pull is disabled (empty source URL, interval 0, or ConfigMap mount mode),
// the policy delivery component writes policiesLoaded=true immediately, so the
// readiness probe does not block a Pod that was never expected to pull.
func runHealthcheck(logger *log.Logger, readiness bool) {
	addr := getenv("AUTHZ_PAP_CLIENT_ADDR", policyadmin.DefaultListenAddr)
	url := "http://" + addr + "/health"

	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		logger.Fatalf("healthcheck failed: %v", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		os.Exit(1)
	}

	if !readiness {
		return
	}

	// Readiness gate: verify that policies were loaded at least once.
	statusFile := getenv("AUTHZ_PULL_STATUS_FILE", policyadmin.DefaultPullStatusFile)
	status, err := policyadmin.LoadPullStatus(statusFile)
	if err != nil {
		logger.Printf("readiness: pull status unavailable (%v) — waiting for first pull", err)
		os.Exit(1)
	}
	if !status.PoliciesLoaded {
		logger.Printf("readiness: policies not yet loaded")
		os.Exit(1)
	}
}

func runBootstrap(logger *log.Logger) {
	policyadmin.RunBootstrap(bootstrapConfigFromEnv(logger))
}

func bootstrapConfigFromEnv(logger *log.Logger) policyadmin.BootstrapConfig {
	return policyadmin.BootstrapConfig{
		TrustedProvidersFile: getenv("AUTHZ_TRUSTED_PROVIDERS_FILE", policyadmin.DefaultTrustedProvidersFile),
		JWKSBootstrapDir:     getenv("AUTHZ_JWKS_BOOTSTRAP_DIR", policyadmin.DefaultJWKSBootstrapDir),
		BootstrapRequired:    envBoolDefault("AUTHZ_JWKS_BOOTSTRAP_REQUIRED", true),
		HTTPTimeout:          time.Duration(envInt64("AUTHZ_JWKS_HTTP_TIMEOUT", int64(policyadmin.DefaultJWKSHTTPTimeout))) * time.Second,
		HTTPRetries:          int(envInt64("AUTHZ_JWKS_HTTP_RETRIES", int64(policyadmin.DefaultJWKSHTTPRetries))),
		StatusFile:           getenv("AUTHZ_JWKS_BOOTSTRAP_STATUS_FILE", policyadmin.DefaultBootstrapStatusFile),
		TenantManagerURL:     getenv("AUTHZ_TENANT_MANAGER_URL", policyadmin.DefaultTenantManagerURL),
		// OPAAuthTokenFile: bootstrap writes {"opa_auth_secret":"<token>"} to the
		// OPA data dir before OPA starts, so system_authz.rego can load it as
		// data.opa_auth_secret at startup (ADR-0077).
		OPAAuthTokenFile: strings.TrimSpace(os.Getenv("AUTHZ_OPA_AUTH_TOKEN_FILE")),
		Logger:           logger,
	}
}

// opaAuthnDataURL points at the `data.authn` document the reloader keeps in
// sync with the trusted-providers file.
func opaAuthnDataURL() string {
	if explicit := strings.TrimSpace(os.Getenv("AUTHZ_PAP_CLIENT_OPA_AUTHN_DATA_URL")); explicit != "" {
		return explicit
	}

	opaAddr := strings.TrimSpace(os.Getenv("OPA_ADDR"))
	if opaAddr == "" {
		opaAddr = "127.0.0.1:8181"
	}

	if strings.HasPrefix(opaAddr, "http://") || strings.HasPrefix(opaAddr, "https://") {
		return strings.TrimRight(opaAddr, "/") + policyadmin.DefaultOPAAuthnDataPath
	}

	return "http://" + opaAddr + policyadmin.DefaultOPAAuthnDataPath
}

func opaDataURL() string {
	if explicit := strings.TrimSpace(os.Getenv("AUTHZ_PAP_CLIENT_OPA_DATA_URL")); explicit != "" {
		return explicit
	}

	opaAddr := strings.TrimSpace(os.Getenv("OPA_ADDR"))
	if opaAddr == "" {
		opaAddr = "127.0.0.1:8181"
	}

	if strings.HasPrefix(opaAddr, "http://") || strings.HasPrefix(opaAddr, "https://") {
		return strings.TrimRight(opaAddr, "/") + "/v1/data/policies"
	}

	return "http://" + opaAddr + "/v1/data/policies"
}
