# Copyright 2024-2026 Netcracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package token_auth_contract_test

import rego.v1

fixtures := data.fixtures.identity
idp_provider_fixture := fixtures.authn.trustedProviders.byId["test-idp"]

policies_fixture := {
  "ols": {
    "CUSTOMER": {
      "READ": ["ROLE_VIEWER"]
    }
  },
  "rls": {
    "CUSTOMER": {
      "READ": {
        "ROLE_VIEWER": [
          {
            "condition": true,
            "predicates": [
              {
                "predicate": "true",
                "type": "rsql"
              }
            ]
          }
        ]
      }
    }
  }
}

runtime_policies_fixture := {
  "ols": {
    "ORDER": {
      "READ": ["ROLE_ADMINISTRATOR", "ROLE_ORDER_MANAGEMENT_RO_USER"]
    }
  },
  "rls": {
    "ORDER": {
      "READ": {
        "ROLE_ADMINISTRATOR": [
          {
            "condition": true,
            "predicates": [
              {
                "predicate": "true",
                "type": "rsql"
              }
            ]
          }
        ],
        "ROLE_ORDER_MANAGEMENT_RO_USER": [
          {
            "conditionAst": {
              "op": "eq",
              "args": [
                {
                  "ref": {
                    "scope": "resource",
                    "path": ["ownerId"]
                  }
                },
                {
                  "ref": {
                    "scope": "subject",
                    "path": ["id"]
                  }
                }
              ]
            },
            "predicates": [
              {
                "predicate": "ownerId==${subject.id}",
                "type": "rsql"
              }
            ]
          }
        ]
      }
    }
  }
}

test_token_auth_valid_user_allows_authorize if {
  token := sprintf("Bearer %v", [fixtures.tokens.valid])
  input_req := {
    "resources": [
      {
        "resourceType": "Customer",
        "operation": "READ",
        "resource": {
          "id": "cust-1"
        }
      }
    ],
    "subject": token,
    "ignoreRls": true
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  actual.rlsIgnored == true
  count(actual.results) == 1
  actual.results[0].isAllowed == true
}

test_token_auth_service_token_subject_type if {
  token := sprintf("Bearer %v", [fixtures.tokens.service])
  auth := data.identity.authenticate({"subject": token}) with data.authn as fixtures.authn
  auth.authenticated
  auth.subject.type == "SERVICE"
}

test_token_auth_naked_subject_token_is_rejected if {
  auth := data.identity.authenticate({"subject": fixtures.tokens.valid}) with data.authn as fixtures.authn
  not auth.authenticated
  auth.error.reasonCode == "TOKEN_SCHEME_INVALID"
}

# The published `data.authn` document is the only supported shape since
# authz-agent-ADR-0075: providers keyed by id, keys keyed by kid. The fixture is
# generated by tests/scripts/token-testkit/refresh-rego-fixtures.sh in exactly
# the layout pap-client writes, so this asserts the contract between the two.
test_token_auth_published_authn_shape_is_supported if {
  token := sprintf("Bearer %v", [fixtures.tokens.valid])

  auth := data.identity.authenticate({"subject": token}) with data.authn as fixtures.authn

  auth.authenticated
  auth.subject.id == "user-allow"
  idp_provider_fixture.required == true
}

test_token_auth_runtime_data_layout_allows_legacy_check_resource if {
  token := sprintf("Bearer %v", [fixtures.tokens.orderReader])
  runtime_authn := fixtures.authn

  input_req := {
    "resources": [{"resourceType": "ORDER", "operation": "READ", "resource": {"id": "order-1", "ownerId": "order-reader-1"}}],
    "subject": token,
    "ignoreRls": true,
  }

  actual := data.authorize
    with input as input_req
    with data.authn as runtime_authn
    with data.policies as runtime_policies_fixture

  actual.results[0].isAllowed == true
}

test_token_auth_verified_tokens_cache_entry_is_trusted_fast_path if {
  cached_token := "cached-token-direct"
  cached_authn := {
    "verifiedTokens": {
      cached_token: {
        "providerId": "cached-idp",
        "subject": {
          "id": "cached-user",
          "name": "cached-user",
          "type": "USER",
          "roles": ["ROLE_VIEWER"],
          "scopes": ["openid"]
        },
        "payload": {
          "sub": "cached-user",
          "preferred_username": "cached-user",
          "realm_access": {
            "roles": ["ROLE_VIEWER"]
          }
        }
      }
    }
  }

  auth := data.identity.authenticate({"subject": sprintf("Bearer %v", [cached_token])}) with data.authn as cached_authn

  auth.authenticated
  auth.subject.id == "cached-user"
  auth.subject.roles == ["ROLE_VIEWER"]
  object.get(auth.subject, "permissions", "__missing__") == "__missing__"
}

test_token_auth_verified_tokens_cache_can_fall_back_to_payload_subject if {
  cached_token := "cached-token-payload-only"
  cached_authn := {
    "verifiedTokens": {
      cached_token: {
        "providerId": "cached-idp",
        "payload": {
          "sub": "payload-user",
          "preferred_username": "payload-user",
          "realm_access": {
            "roles": ["ROLE_VIEWER"]
          },
          "scope": "openid profile"
        }
      }
    }
  }

  auth := data.identity.authenticate({"subject": sprintf("Bearer %v", [cached_token])}) with data.authn as cached_authn

  auth.authenticated
  auth.subject.id == "payload-user"
  auth.subject.name == "payload-user"
  auth.subject.roles == ["ROLE_VIEWER"]
  auth.subject.scopes == ["openid", "profile"]
  object.get(auth.subject, "permissions", "__missing__") == "__missing__"
}

# ── Canonical: no authorizationToken -> subject invalid -> 200 DENY ───────

test_token_auth_missing_token_canonical_deny if {
  input_req := {
    "resources": [
      {
        "resourceType": "Customer",
        "operation": "READ",
        "resource": {}
      }
    ],
    "subject": "",
    "ignoreRls": true
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  not object.get(actual, "authError", false)
  count(actual.results) == 1
  actual.results[0].isAllowed == false
  actual.results[0].reason == "Authorization token is missing"
}

test_token_auth_expired_canonical_deny if {
  token := sprintf("Bearer %v", [fixtures.tokens.expired])
  input_req := {
    "resources": [
      {
        "resourceType": "Customer",
        "operation": "READ",
        "resource": {}
      }
    ],
    "subject": token,
    "ignoreRls": true
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  not object.get(actual, "authError", false)
  count(actual.results) == 1
  actual.results[0].isAllowed == false
  actual.results[0].reason == "Token has expired"
}

# The `iss` claim stopped being a trust criterion in authz-agent-ADR-0075: this
# token is signed by the same key with the same kid and differs only in issuer,
# so it authenticates and the decision comes from the policy instead.
test_token_auth_foreign_issuer_canonical_allow if {
  token := sprintf("Bearer %v", [fixtures.tokens.wrongIssuer])
  input_req := {
    "resources": [
      {
        "resourceType": "Customer",
        "operation": "READ",
        "resource": {}
      }
    ],
    "subject": token,
    "ignoreRls": true
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  not object.get(actual, "authError", false)
  count(actual.results) == 1
  actual.results[0].isAllowed == true
}

test_token_auth_unknown_kid_canonical_deny if {
  token := sprintf("Bearer %v", [fixtures.tokens.unknownKid])
  input_req := {
    "resources": [
      {
        "resourceType": "Customer",
        "operation": "READ",
        "resource": {}
      }
    ],
    "subject": token,
    "ignoreRls": true
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  not object.get(actual, "authError", false)
  count(actual.results) == 1
  actual.results[0].isAllowed == false
  actual.results[0].reason == "JWT kid is not found in trusted provider keys"
}

# ── Legacy: invalid subject token -> 401 authError ──────────────────────

test_token_auth_missing_token_legacy_auth_error if {
  input_req := {
    "resources": [{"resourceType": "Customer", "operation": "READ", "resource": {}}],
    "subject": "",
    "ignoreRls": true,
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  actual.results[0].isAllowed == false
  actual.results[0].reason == "Authorization token is missing"
}

test_token_auth_expired_legacy_auth_error if {
  token := sprintf("Bearer %v", [fixtures.tokens.expired])
  input_req := {
    "authorizationToken": token,
    "resources": [{"resourceType": "Customer", "operation": "READ", "resource": {}}],
    "subject": token,
    "ignoreRls": true,
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  auth_error := object.get(actual, "authError", {})
  object.get(auth_error, "status", 0) == 401
  object.get(auth_error, "reason", "") == "Token has expired"
}

test_token_auth_no_roles_is_authenticated_but_denied if {
  token := sprintf("Bearer %v", [fixtures.tokens.noRoles])
  input_req := {
    "resources": [
      {
        "resourceType": "Customer",
        "operation": "READ",
        "resource": {}
      }
    ],
    "subject": token,
    "ignoreRls": true
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  not object.get(actual, "authError", false)
  count(actual.results) == 1
  actual.results[0].isAllowed == false
}

test_token_auth_object_subject_without_internal_flag_is_rejected if {
  input_req := {
    "resources": [
      {
        "resourceType": "Customer",
        "operation": "READ",
        "resource": {}
      }
    ],
    "subject": {
      "id": "manual",
      "type": "USER",
      "roles": ["ROLE_VIEWER"]
    },
    "ignoreRls": true
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  not object.get(actual, "authError", false)
  count(actual.results) == 1
  actual.results[0].isAllowed == false
}

test_token_auth_object_subject_with_internal_flag_is_still_rejected if {
  input_req := {
    "resources": [
      {
        "resourceType": "Customer",
        "operation": "READ",
        "resource": {}
      }
    ],
    "subject": {
      "id": "manual",
      "type": "USER",
      "roles": ["ROLE_VIEWER"]
    },
    "internalSubject": true,
    "ignoreRls": true
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  not object.get(actual, "authError", false)
  count(actual.results) == 1
  actual.results[0].isAllowed == false
}

# ── realm_access.roles positive cases ────────────────────────────────────

test_token_auth_realm_access_roles_are_used if {
  payload := {
    "realm_access": {
      "roles": ["ROLE_VIEWER", "ROLE_EDITOR"]
    }
  }
  roles := data.identity.payload_roles(payload)
  count(roles) == 2
  roles[0] == "ROLE_EDITOR"
  roles[1] == "ROLE_VIEWER"
}

test_token_auth_realm_access_roles_are_case_normalized if {
  payload := {
    "realm_access": {
      "roles": ["role_viewer", "Role_Editor"]
    }
  }
  roles := data.identity.payload_roles(payload)
  count(roles) == 2
  roles[0] == "ROLE_EDITOR"
  roles[1] == "ROLE_VIEWER"
}

# ── ignored non-realm claim negative cases ───────────────────────────────

test_token_auth_groups_without_realm_access_gives_no_roles if {
  payload := {
    "groups": ["ROLE_ADMINISTRATOR", "ROLE_VIEWER"]
  }
  roles := data.identity.payload_roles(payload)
  count(roles) == 0
}

test_token_auth_direct_roles_without_realm_access_gives_no_roles if {
  payload := {
    "roles": ["ROLE_ADMINISTRATOR", "ROLE_VIEWER"]
  }
  roles := data.identity.payload_roles(payload)
  count(roles) == 0
}

test_token_auth_authorities_without_realm_access_gives_no_roles if {
  payload := {
    "authorities": ["ROLE_ADMINISTRATOR", "ROLE_VIEWER"]
  }
  roles := data.identity.payload_roles(payload)
  count(roles) == 0
}

test_token_auth_resource_access_without_realm_access_gives_no_roles if {
  payload := {
    "resource_access": {
      "portal": {
        "roles": ["ROLE_ADMINISTRATOR", "ROLE_VIEWER"]
      }
    }
  }
  roles := data.identity.payload_roles(payload)
  count(roles) == 0
}

test_token_auth_all_non_realm_claims_without_realm_access_gives_no_roles if {
  payload := {
    "roles": ["ROLE_VIEWER"],
    "authorities": ["ROLE_VIEWER"],
    "groups": ["ROLE_VIEWER"],
    "resource_access": {
      "portal": {
        "roles": ["ROLE_VIEWER"]
      }
    }
  }
  roles := data.identity.payload_roles(payload)
  count(roles) == 0
}

test_token_auth_empty_realm_access_roles_gives_no_roles if {
  payload := {
    "realm_access": {
      "roles": []
    }
  }
  roles := data.identity.payload_roles(payload)
  count(roles) == 0
}

test_token_auth_missing_realm_access_gives_no_roles if {
  payload := {}
  roles := data.identity.payload_roles(payload)
  count(roles) == 0
}

test_token_auth_non_realm_claims_ignored_even_when_realm_access_present if {
  payload := {
    "roles": ["ROLE_EXTRA_DIRECT"],
    "authorities": ["ROLE_EXTRA_AUTHORITY"],
    "groups": ["ROLE_EXTRA_GROUP"],
    "resource_access": {
      "portal": {
        "roles": ["ROLE_EXTRA_SERVICE"]
      }
    },
    "realm_access": {
      "roles": ["ROLE_VIEWER"]
    }
  }
  roles := data.identity.payload_roles(payload)
  count(roles) == 1
  roles[0] == "ROLE_VIEWER"
}

test_token_auth_groups_only_token_is_denied_for_authorization if {
  token := sprintf("Bearer %v", [fixtures.tokens.groupsOnlyOrderReader])
  input_req := {
    "resources": [{"resourceType": "Customer", "operation": "READ", "resource": {}}],
    "subject": token,
    "ignoreRls": true,
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  actual.results[0].isAllowed == false
}

# ── many-roles deduplication and matching ────────────────────────────────

test_token_auth_many_roles_payload_is_deduplicated_and_authorizes_by_matching_role if {
  payload := payload_with_many_roles_and_match
  roles := data.identity.payload_roles(payload)
  role_set := data.authorize_internals.subject_roles_set({"roles": roles})

  count(roles) == 41
  count(roles) == count({role | role := roles[_]})
  count([1 |
    some idx
    roles[idx] == "ROLE_VIEWER"
  ]) == 1

  ols := data.ols.evaluate("CUSTOMER", "READ", role_set) with data.policies as policies_fixture
  ols.allow
  ols.roles == ["ROLE_VIEWER"]
}

test_token_auth_many_roles_payload_without_required_role_is_denied if {
  payload := payload_with_many_roles_without_match
  roles := data.identity.payload_roles(payload)
  role_set := data.authorize_internals.subject_roles_set({"roles": roles})

  count(roles) == 40
  not role_set["ROLE_VIEWER"]

  ols := data.ols.evaluate("CUSTOMER", "READ", role_set) with data.policies as policies_fixture
  not ols.allow
}

test_token_auth_many_roles_normalize_case_and_deduplicate if {
  payload := payload_with_many_roles_case_folded_duplicates
  roles := data.identity.payload_roles(payload)
  role_set := data.authorize_internals.subject_roles_set({"roles": roles})

  count(roles) == 41
  count(roles) == count({role | role := roles[_]})
  count([1 |
    some idx
    roles[idx] == "ROLE_VIEWER"
  ]) == 1
  count([1 |
    some idx
    roles[idx] == "role_viewer"
  ]) == 0
  role_set["ROLE_VIEWER"]
}

# ── anonymous mode ───────────────────────────────────────────────────────

test_token_auth_anonymous_mode_is_authenticated if {
  input_req := {
    "resources": [{"resourceType": "Customer", "operation": "READ", "resource": {}}],
    "subject": "",
    "authorizationType": "anonymous",
    "ignoreRls": true,
  }

  actual := data.authorize
    with input as input_req
    with data.authn as fixtures.authn
    with data.policies as policies_fixture

  actual.results[0].isAllowed == false
}

test_token_auth_anonymous_subject_has_no_permissions_field if {
  auth := data.identity.authenticate({
    "subject": "",
    "authorizationType": "anonymous",
  }) with data.authn as fixtures.authn

  auth.authenticated
  auth.subject.type == "ANONYMOUS"
  object.get(auth.subject, "permissions", "__missing__") == "__missing__"
}

# ── helper payloads ──────────────────────────────────────────────────────

payload_with_many_roles_and_match := {
  "roles": ["ROLE_VIEWER"],
  "authorities": ["ROLE_VIEWER"],
  "groups": ["ROLE_VIEWER"],
  "realm_access": {
    "roles": array.concat(["ROLE_VIEWER"], generated_roles("ROLE_REALM_", 1, 40))
  },
  "resource_access": {
    "portal": {
      "roles": ["ROLE_VIEWER"]
    }
  }
}

payload_with_many_roles_without_match := {
  "roles": ["ROLE_VIEWER"],
  "authorities": ["ROLE_VIEWER"],
  "groups": ["ROLE_VIEWER"],
  "realm_access": {
    "roles": generated_roles("ROLE_REALM_", 1, 40)
  },
  "resource_access": {
    "portal": {
      "roles": ["ROLE_VIEWER"]
    }
  }
}

payload_with_many_roles_case_folded_duplicates := {
  "roles": ["role_viewer"],
  "authorities": ["Role_Viewer"],
  "groups": ["ROLE_VIEWER"],
  "realm_access": {
    "roles": array.concat(["role_viewer", "Role_Viewer", "ROLE_VIEWER"], generated_roles("ROLE_REALM_", 1, 40))
  },
  "resource_access": {
    "portal": {
      "roles": ["ROLE_VIEWER"]
    }
  }
}

generated_roles(prefix, start, finish) := [sprintf("%v%03d", [prefix, idx]) |
  idx := numbers.range(start, finish)[_]
]

# ── ADR-0046: Canonical-only subject contract ──────────────────────────────

test_subject_contains_only_canonical_fields if {
  token := sprintf("Bearer %v", [fixtures.tokens.valid])
  auth := data.identity.authenticate({"subject": token}) with data.authn as fixtures.authn
  auth.authenticated

  subject_keys := object.keys(auth.subject)
  canonical_keys := {"id", "name", "type", "roles", "scopes"}
  extra_keys := {k | k := subject_keys[_]; not canonical_keys[k]}
  print({"extra_keys_in_subject": extra_keys})
  count(extra_keys) == 0
}

test_subject_from_cached_verification_contains_only_canonical_fields if {
  cached_token := "cached-token-extra-claims"
  cached_authn := {
    "verifiedTokens": {
      cached_token: {
        "providerId": "cached-idp",
        "subject": {
          "id": "cached-user",
          "name": "cached-user",
          "type": "USER",
          "roles": ["ROLE_VIEWER"],
          "scopes": ["openid"],
          "email": "cached@test.local",
          "department": "engineering"
        },
        "payload": {
          "sub": "cached-user",
          "preferred_username": "cached-user",
          "realm_access": {"roles": ["ROLE_VIEWER"]},
          "email": "cached@test.local",
          "department": "engineering"
        }
      }
    }
  }

  auth := data.identity.authenticate({"subject": sprintf("Bearer %v", [cached_token])}) with data.authn as cached_authn
  auth.authenticated

  subject_keys := object.keys(auth.subject)
  canonical_keys := {"id", "name", "type", "roles", "scopes"}
  extra_keys := {k | k := subject_keys[_]; not canonical_keys[k]}
  print({"extra_keys_in_cached_subject": extra_keys})
  count(extra_keys) == 0
}

test_authenticate_returns_token_payload if {
  token := sprintf("Bearer %v", [fixtures.tokens.valid])
  auth := data.identity.authenticate({"subject": token}) with data.authn as fixtures.authn
  auth.authenticated

  payload := object.get(auth, "tokenPayload", {})
  count(object.keys(payload)) > 0
  payload.sub == "user-allow"
}

# ── ADR-0046: TOKEN PIP end-to-end authorization tests ─────────────────────

test_token_pip_e2e_positive_predicate_uses_alias if {
  cached_token := "pip-e2e-token"
  cached_authn := {
    "verifiedTokens": {
      cached_token: {
        "providerId": "test-idp",
        "subject": {
          "id": "pip-user",
          "name": "pip-user",
          "type": "USER",
          "roles": ["ROLE_USER"],
          "scopes": []
        },
        "payload": {
          "sub": "pip-user",
          "preferred_username": "pip-user",
          "realm_access": {"roles": ["ROLE_USER"]},
          "email": "pip-user@test.local"
        }
      }
    }
  }

  pip_config := {
    "local": {
      "token": {
        "subject.emailFromToken": {
          "name": "subject.emailFromToken",
          "alias": "emailFromToken",
          "claim": "email"
        }
      },
      "header": {}
    },
    "remote": {"general": {}},
    "activation": {"generalByResourceTypeOperation": {}},
    "byName": {
      "subject.emailFromToken": {
        "type": "TOKEN",
        "name": "subject.emailFromToken",
        "alias": "emailFromToken",
        "claim": "email"
      }
    },
    "aliasSet": {"emailFromToken": true}
  }

  policies := {
    "ols": {
      "ORDER": {"READ": ["ROLE_USER"]}
    },
    "rls": {
      "ORDER": {
        "READ": {
          "ROLE_USER": [{
            "conditionAst": {
              "op": "eq",
              "args": [
                {"ref": {"scope": "resource", "path": ["ownerEmail"]}},
                {"ref": {"scope": "subject", "path": ["emailFromToken"]}}
              ]
            },
            "predicates": [{"predicate": "ownerEmail==${subject.emailFromToken}", "type": "rsql"}]
          }]
        }
      }
    }
  }

  input_req := {
    "resources": [{"resourceType": "ORDER", "operation": "READ", "resource": {"ownerEmail": "pip-user@test.local"}}],
    "subject": sprintf("Bearer %v", [cached_token]),
    "ignoreRls": false
  }

  actual := data.authorize
    with input as input_req
    with data.authn as cached_authn
    with data.policies as policies
    with data.pips as pip_config

  count(actual.results) == 1
  actual.results[0].isAllowed == true
  # D-AF-R (OQ-AF-6, 2026-04-15): scalar string substitution is
  # JSON-quoted in the rendered predicate per the legacy parity
  # contract.
  actual.results[0].predicates[0].predicate == `ownerEmail=="pip-user@test.local"`
}

test_token_pip_e2e_fallback_default_value if {
  cached_token := "pip-e2e-no-email-token"
  cached_authn := {
    "verifiedTokens": {
      cached_token: {
        "providerId": "test-idp",
        "subject": {
          "id": "pip-user-no-email",
          "name": "pip-user-no-email",
          "type": "USER",
          "roles": ["ROLE_USER"],
          "scopes": []
        },
        "payload": {
          "sub": "pip-user-no-email",
          "preferred_username": "pip-user-no-email",
          "realm_access": {"roles": ["ROLE_USER"]}
        }
      }
    }
  }

  pip_config := {
    "local": {
      "token": {
        "subject.emailFromToken": {
          "name": "subject.emailFromToken",
          "alias": "emailFromToken",
          "claim": "email",
          "defaultValue": "unknown@fallback"
        }
      },
      "header": {}
    },
    "remote": {"general": {}},
    "activation": {"generalByResourceTypeOperation": {}},
    "byName": {
      "subject.emailFromToken": {
        "type": "TOKEN",
        "name": "subject.emailFromToken",
        "alias": "emailFromToken",
        "claim": "email",
        "defaultValue": "unknown@fallback"
      }
    },
    "aliasSet": {"emailFromToken": true}
  }

  policies := {
    "ols": {
      "ORDER": {"READ": ["ROLE_USER"]}
    },
    "rls": {
      "ORDER": {
        "READ": {
          "ROLE_USER": [{
            "condition": true,
            "predicates": [{"predicate": "ownerEmail==${subject.emailFromToken}", "type": "rsql"}]
          }]
        }
      }
    }
  }

  input_req := {
    "resources": [{"resourceType": "ORDER", "operation": "READ", "resource": {}}],
    "subject": sprintf("Bearer %v", [cached_token]),
    "ignoreRls": false
  }

  actual := data.authorize
    with input as input_req
    with data.authn as cached_authn
    with data.policies as policies
    with data.pips as pip_config

  count(actual.results) == 1
  actual.results[0].isAllowed == true
  # D-AF-R: scalar string (PIP default value) is JSON-quoted.
  actual.results[0].predicates[0].predicate == `ownerEmail=="unknown@fallback"`
}

test_token_pip_e2e_unconfigured_claim_not_in_subject if {
  cached_token := "pip-e2e-no-pip-token"
  cached_authn := {
    "verifiedTokens": {
      cached_token: {
        "providerId": "test-idp",
        "subject": {
          "id": "pip-user",
          "name": "pip-user",
          "type": "USER",
          "roles": ["ROLE_USER"],
          "scopes": []
        },
        "payload": {
          "sub": "pip-user",
          "preferred_username": "pip-user",
          "realm_access": {"roles": ["ROLE_USER"]},
          "email": "pip-user@test.local",
          "department": "engineering"
        }
      }
    }
  }

  policies := {
    "ols": {
      "ORDER": {"READ": ["ROLE_USER"]}
    },
    "rls": {
      "ORDER": {
        "READ": {
          "ROLE_USER": [{
            "conditionAst": {
              "op": "eq",
              "args": [
                {"ref": {"scope": "resource", "path": ["dept"]}},
                {"ref": {"scope": "subject", "path": ["department"]}}
              ]
            },
            "predicates": [{"predicate": "dept==${subject.department}", "type": "rsql"}]
          }]
        }
      }
    }
  }

  input_req := {
    "resources": [{"resourceType": "ORDER", "operation": "READ", "resource": {"dept": "engineering"}}],
    "subject": sprintf("Bearer %v", [cached_token]),
    "ignoreRls": false
  }

  actual := data.authorize
    with input as input_req
    with data.authn as cached_authn
    with data.policies as policies

  count(actual.results) == 1
  actual.results[0].isAllowed == false
  contains(actual.results[0].reason, "subject attribute not found: department")
}
